import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "../../core/components/warpper/header/Header";
import ArticleGrid from "../../core/components/grid/ArticleGrid";
import Pregrid from "../../core/components/grid/Pregrid";

const inter = Inter({ subsets: ["latin"] });

const testArticles = [
  {
    name: "TestTest",
    imageScr:
      "https://fastly.picsum.photos/id/952/500/300.jpg?hmac=YgoTM__VzyTDC1kTCFxM-Bc0WseGsbdkUMBKoDbyOTc",
    specialPrice: "25.99€",
    oldPrice: "22.99€",
  },
  {
    name: "TestTest",
    imageScr:
      "https://fastly.picsum.photos/id/952/500/300.jpg?hmac=YgoTM__VzyTDC1kTCFxM-Bc0WseGsbdkUMBKoDbyOTc",
    specialPrice: "25.99€",
    oldPrice: "22.99€",
  },
  {
    name: "TestTest",
    imageScr:
      "https://fastly.picsum.photos/id/952/500/300.jpg?hmac=YgoTM__VzyTDC1kTCFxM-Bc0WseGsbdkUMBKoDbyOTc",
    specialPrice: "25.99€",
    oldPrice: "22.99€",
  },
  {
    name: "TestTest",
    imageScr:
      "https://fastly.picsum.photos/id/952/500/300.jpg?hmac=YgoTM__VzyTDC1kTCFxM-Bc0WseGsbdkUMBKoDbyOTc",
    specialPrice: "25.99€",
    oldPrice: "22.99€",
  },
  {
    name: "TestTest",
    imageScr:
      "https://fastly.picsum.photos/id/952/500/300.jpg?hmac=YgoTM__VzyTDC1kTCFxM-Bc0WseGsbdkUMBKoDbyOTc",
    specialPrice: "25.99€",
    oldPrice: "22.99€",
  },
  {
    name: "TestTest",
    imageScr:
      "https://fastly.picsum.photos/id/952/500/300.jpg?hmac=YgoTM__VzyTDC1kTCFxM-Bc0WseGsbdkUMBKoDbyOTc",
    specialPrice: "25.99€",
    oldPrice: "22.99€",
  },
  {
    name: "TestTest",
    imageScr:
      "https://fastly.picsum.photos/id/952/500/300.jpg?hmac=YgoTM__VzyTDC1kTCFxM-Bc0WseGsbdkUMBKoDbyOTc",
    specialPrice: "25.99€",
    oldPrice: "22.99€",
  },
  {
    name: "TestTest",
    imageScr:
      "https://fastly.picsum.photos/id/952/500/300.jpg?hmac=YgoTM__VzyTDC1kTCFxM-Bc0WseGsbdkUMBKoDbyOTc",
    specialPrice: "25.99€",
    oldPrice: "22.99€",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>SALES - War of Mind</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Pregrid />
      {/* <ArticleGrid articles={testArticles} /> */}
    </>
  );
}
