import Head from "next/head";
import Header from "../../core/components/warpper/header/Header";
import ProductGrid from "../../core/components/grid/ProductGrid";
import productList from "../../public/static/products/productList.json";
import { IBrand } from "../../core/entities/brand";
import Footer from "../../core/components/warpper/footer/Footer";
import ProductParser from "../../core/adapters/ParseProducts";

//write a parse which takes the json and returns an array of IArticle
//then you can use the array in the ArticleGrid component
// how to parse a json file to a javascript object
// https://stackoverflow.com/questions/20008134/how-to-parse-a-json-file-in-javascript

export default function Home(props: IBrand) {
  return (
    <>
      <Head>
        <title>SALES - War of Mind</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductGrid products={props} />
    </>
  );
}

export async function getStaticProps() {
  const productParser = new ProductParser();
  const products = productParser.parse(productList);
  return {
    props: {
      ...products,
    },
  };
}
